### ISSUE TITLE
Пробел

### ISSUE THREAD

**Issue by Nifacy** [Sh0kerr/data_analysis#1]
[Пробел](https://github.com/Sh0kerr/data_analysis/blob/ea4b0fd95d42c945c012da75ebc62176b7b397aa/lw_1/utils.py#L28) (просьба поправить)

<img width="507" alt="image" src="https://github.com/user-attachments/assets/ca78e704-7874-402d-98f6-fb9cd878e90c">

**Comment by Sh0kerr** [comment]
Готово! Рад, что мой невъебенный open source проект притягивает внимание неравнодушных! Стараемся! Окрошка! Гинзберг! МаКаН!
